/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleLifecycleState } from './ArticleLifecycleState';
import {
    ArticleLifecycleStateFromJSON,
    ArticleLifecycleStateFromJSONTyped,
    ArticleLifecycleStateToJSON,
    ArticleLifecycleStateToJSONTyped,
} from './ArticleLifecycleState';
import type { ArticleCoverMedia } from './ArticleCoverMedia';
import {
    ArticleCoverMediaFromJSON,
    ArticleCoverMediaFromJSONTyped,
    ArticleCoverMediaToJSON,
    ArticleCoverMediaToJSONTyped,
} from './ArticleCoverMedia';
import type { ArticleMetadata } from './ArticleMetadata';
import {
    ArticleMetadataFromJSON,
    ArticleMetadataFromJSONTyped,
    ArticleMetadataToJSON,
    ArticleMetadataToJSONTyped,
} from './ArticleMetadata';

/**
 * 
 * @export
 * @interface ArticleResult
 */
export interface ArticleResult {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ArticleResult
     */
    contentState?: { [key: string]: any; };
    /**
     * 
     * @type {ArticleCoverMedia}
     * @memberof ArticleResult
     */
    coverMedia?: ArticleCoverMedia;
    /**
     * 
     * @type {string}
     * @memberof ArticleResult
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleResult
     */
    isGrokSummaryEligible?: boolean;
    /**
     * 
     * @type {ArticleLifecycleState}
     * @memberof ArticleResult
     */
    lifecycleState?: ArticleLifecycleState;
    /**
     * 
     * @type {Array<ArticleCoverMedia>}
     * @memberof ArticleResult
     */
    mediaEntities?: Array<ArticleCoverMedia>;
    /**
     * 
     * @type {ArticleMetadata}
     * @memberof ArticleResult
     */
    metadata: ArticleMetadata;
    /**
     * 
     * @type {string}
     * @memberof ArticleResult
     */
    previewText: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleResult
     */
    restId: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleResult
     */
    title: string;
}

/**
 * Check if a given object implements the ArticleResult interface.
 */
export function instanceOfArticleResult(value: object): value is ArticleResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('previewText' in value) || value['previewText'] === undefined) return false;
    if (!('restId' in value) || value['restId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ArticleResultFromJSON(json: any): ArticleResult {
    return ArticleResultFromJSONTyped(json, false);
}

export function ArticleResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleResult {
    if (json == null) {
        return json;
    }
    return {
        
        'contentState': json['content_state'] == null ? undefined : json['content_state'],
        'coverMedia': json['cover_media'] == null ? undefined : ArticleCoverMediaFromJSON(json['cover_media']),
        'id': json['id'],
        'isGrokSummaryEligible': json['is_grok_summary_eligible'] == null ? undefined : json['is_grok_summary_eligible'],
        'lifecycleState': json['lifecycle_state'] == null ? undefined : ArticleLifecycleStateFromJSON(json['lifecycle_state']),
        'mediaEntities': json['media_entities'] == null ? undefined : ((json['media_entities'] as Array<any>).map(ArticleCoverMediaFromJSON)),
        'metadata': ArticleMetadataFromJSON(json['metadata']),
        'previewText': json['preview_text'],
        'restId': json['rest_id'],
        'title': json['title'],
    };
}

export function ArticleResultToJSON(json: any): ArticleResult {
    return ArticleResultToJSONTyped(json, false);
}

export function ArticleResultToJSONTyped(value?: ArticleResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_state': value['contentState'],
        'cover_media': ArticleCoverMediaToJSON(value['coverMedia']),
        'id': value['id'],
        'is_grok_summary_eligible': value['isGrokSummaryEligible'],
        'lifecycle_state': ArticleLifecycleStateToJSON(value['lifecycleState']),
        'media_entities': value['mediaEntities'] == null ? undefined : ((value['mediaEntities'] as Array<any>).map(ArticleCoverMediaToJSON)),
        'metadata': ArticleMetadataToJSON(value['metadata']),
        'preview_text': value['previewText'],
        'rest_id': value['restId'],
        'title': value['title'],
    };
}

