/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleCoverMedia } from './ArticleCoverMedia';
import {
    ArticleCoverMediaFromJSON,
    ArticleCoverMediaFromJSONTyped,
    ArticleCoverMediaToJSON,
    ArticleCoverMediaToJSONTyped,
} from './ArticleCoverMedia';

/**
 * 
 * @export
 * @interface ArticlePreview
 */
export interface ArticlePreview {
    /**
     * 
     * @type {number}
     * @memberof ArticlePreview
     */
    articleId: number;
    /**
     * 
     * @type {ArticleCoverMedia}
     * @memberof ArticlePreview
     */
    coverMedia?: ArticleCoverMedia;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    previewText: string;
    /**
     * 
     * @type {string}
     * @memberof ArticlePreview
     */
    title: string;
}

/**
 * Check if a given object implements the ArticlePreview interface.
 */
export function instanceOfArticlePreview(value: object): value is ArticlePreview {
    if (!('articleId' in value) || value['articleId'] === undefined) return false;
    if (!('previewText' in value) || value['previewText'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function ArticlePreviewFromJSON(json: any): ArticlePreview {
    return ArticlePreviewFromJSONTyped(json, false);
}

export function ArticlePreviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlePreview {
    if (json == null) {
        return json;
    }
    return {
        
        'articleId': json['article_id'],
        'coverMedia': json['cover_media'] == null ? undefined : ArticleCoverMediaFromJSON(json['cover_media']),
        'previewText': json['preview_text'],
        'title': json['title'],
    };
}

export function ArticlePreviewToJSON(json: any): ArticlePreview {
    return ArticlePreviewToJSONTyped(json, false);
}

export function ArticlePreviewToJSONTyped(value?: ArticlePreview | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article_id': value['articleId'],
        'cover_media': ArticleCoverMediaToJSON(value['coverMedia']),
        'preview_text': value['previewText'],
        'title': value['title'],
    };
}

