/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunityResult } from './CommunityResult';
import {
    CommunityResultFromJSON,
    CommunityResultFromJSONTyped,
    CommunityResultToJSON,
    CommunityResultToJSONTyped,
} from './CommunityResult';
import type { UserResults } from './UserResults';
import {
    UserResultsFromJSON,
    UserResultsFromJSONTyped,
    UserResultsToJSON,
    UserResultsToJSONTyped,
} from './UserResults';

/**
 * 
 * @export
 * @interface AuthorCommunityRelationship
 */
export interface AuthorCommunityRelationship {
    /**
     * 
     * @type {CommunityResult}
     * @memberof AuthorCommunityRelationship
     */
    communityResults: CommunityResult;
    /**
     * 
     * @type {AuthorCommunityRelationshipRoleEnum}
     * @memberof AuthorCommunityRelationship
     */
    role?: AuthorCommunityRelationshipRoleEnum;
    /**
     * 
     * @type {UserResults}
     * @memberof AuthorCommunityRelationship
     */
    userResults?: UserResults;
}


/**
 * @export
 */
export const AuthorCommunityRelationshipRoleEnum = {
    Member: 'Member',
    Moderator: 'Moderator',
    Admin: 'Admin',
    NonMember: 'NonMember'
} as const;
export type AuthorCommunityRelationshipRoleEnum = typeof AuthorCommunityRelationshipRoleEnum[keyof typeof AuthorCommunityRelationshipRoleEnum];


/**
 * Check if a given object implements the AuthorCommunityRelationship interface.
 */
export function instanceOfAuthorCommunityRelationship(value: object): value is AuthorCommunityRelationship {
    if (!('communityResults' in value) || value['communityResults'] === undefined) return false;
    return true;
}

export function AuthorCommunityRelationshipFromJSON(json: any): AuthorCommunityRelationship {
    return AuthorCommunityRelationshipFromJSONTyped(json, false);
}

export function AuthorCommunityRelationshipFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorCommunityRelationship {
    if (json == null) {
        return json;
    }
    return {
        
        'communityResults': CommunityResultFromJSON(json['community_results']),
        'role': json['role'] == null ? undefined : json['role'],
        'userResults': json['user_results'] == null ? undefined : UserResultsFromJSON(json['user_results']),
    };
}

export function AuthorCommunityRelationshipToJSON(json: any): AuthorCommunityRelationship {
    return AuthorCommunityRelationshipToJSONTyped(json, false);
}

export function AuthorCommunityRelationshipToJSONTyped(value?: AuthorCommunityRelationship | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'community_results': CommunityResultToJSON(value['communityResults']),
        'role': value['role'],
        'user_results': UserResultsToJSON(value['userResults']),
    };
}

