/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrokTranslatedCommunityNoteWithAvailability } from './GrokTranslatedCommunityNoteWithAvailability';
import {
    GrokTranslatedCommunityNoteWithAvailabilityFromJSON,
    GrokTranslatedCommunityNoteWithAvailabilityFromJSONTyped,
    GrokTranslatedCommunityNoteWithAvailabilityToJSON,
    GrokTranslatedCommunityNoteWithAvailabilityToJSONTyped,
} from './GrokTranslatedCommunityNoteWithAvailability';

/**
 * 
 * @export
 * @interface BirdwatchPivotNote
 */
export interface BirdwatchPivotNote {
    /**
     * 
     * @type {GrokTranslatedCommunityNoteWithAvailability}
     * @memberof BirdwatchPivotNote
     */
    grokTranslatedCommunityNoteWithAvailability?: GrokTranslatedCommunityNoteWithAvailability;
    /**
     * 
     * @type {boolean}
     * @memberof BirdwatchPivotNote
     */
    isCommunityNoteTranslatable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BirdwatchPivotNote
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof BirdwatchPivotNote
     */
    restId: string;
}

/**
 * Check if a given object implements the BirdwatchPivotNote interface.
 */
export function instanceOfBirdwatchPivotNote(value: object): value is BirdwatchPivotNote {
    if (!('restId' in value) || value['restId'] === undefined) return false;
    return true;
}

export function BirdwatchPivotNoteFromJSON(json: any): BirdwatchPivotNote {
    return BirdwatchPivotNoteFromJSONTyped(json, false);
}

export function BirdwatchPivotNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): BirdwatchPivotNote {
    if (json == null) {
        return json;
    }
    return {
        
        'grokTranslatedCommunityNoteWithAvailability': json['grok_translated_community_note_with_availability'] == null ? undefined : GrokTranslatedCommunityNoteWithAvailabilityFromJSON(json['grok_translated_community_note_with_availability']),
        'isCommunityNoteTranslatable': json['is_community_note_translatable'] == null ? undefined : json['is_community_note_translatable'],
        'language': json['language'] == null ? undefined : json['language'],
        'restId': json['rest_id'],
    };
}

export function BirdwatchPivotNoteToJSON(json: any): BirdwatchPivotNote {
    return BirdwatchPivotNoteToJSONTyped(json, false);
}

export function BirdwatchPivotNoteToJSONTyped(value?: BirdwatchPivotNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'grok_translated_community_note_with_availability': GrokTranslatedCommunityNoteWithAvailabilityToJSON(value['grokTranslatedCommunityNoteWithAvailability']),
        'is_community_note_translatable': value['isCommunityNoteTranslatable'],
        'language': value['language'],
        'rest_id': value['restId'],
    };
}

