/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Community } from './Community';
import {
    instanceOfCommunity,
    CommunityFromJSON,
    CommunityFromJSONTyped,
    CommunityToJSON,
} from './Community';
import type { CommunityUnavailable } from './CommunityUnavailable';
import {
    instanceOfCommunityUnavailable,
    CommunityUnavailableFromJSON,
    CommunityUnavailableFromJSONTyped,
    CommunityUnavailableToJSON,
} from './CommunityUnavailable';

/**
 * @type CommunityUnion
 * 
 * @export
 */
export type CommunityUnion = { typename: 'Community' } & Community | { typename: 'CommunityUnavailable' } & CommunityUnavailable;

export function CommunityUnionFromJSON(json: any): CommunityUnion {
    return CommunityUnionFromJSONTyped(json, false);
}

export function CommunityUnionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityUnion {
    if (json == null) {
        return json;
    }
    switch (json['__typename']) {
        case 'Community':
            return Object.assign({}, CommunityFromJSONTyped(json, true), { typename: 'Community' } as const);
        case 'CommunityUnavailable':
            return Object.assign({}, CommunityUnavailableFromJSONTyped(json, true), { typename: 'CommunityUnavailable' } as const);
        default:
            return json;
    }
}

export function CommunityUnionToJSON(json: any): any {
    return CommunityUnionToJSONTyped(json, false);
}

export function CommunityUnionToJSONTyped(value?: CommunityUnion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['typename']) {
        case 'Community':
            return Object.assign({}, CommunityToJSON(value), { typename: 'Community' } as const);
        case 'CommunityUnavailable':
            return Object.assign({}, CommunityUnavailableToJSON(value), { typename: 'CommunityUnavailable' } as const);
        default:
            return value;
    }
}

