/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';

/**
 * 
 * @export
 * @interface CommunityUnavailable
 */
export interface CommunityUnavailable {
    /**
     * 
     * @type {TypeName}
     * @memberof CommunityUnavailable
     */
    typename: TypeName;
}



/**
 * Check if a given object implements the CommunityUnavailable interface.
 */
export function instanceOfCommunityUnavailable(value: object): value is CommunityUnavailable {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    return true;
}

export function CommunityUnavailableFromJSON(json: any): CommunityUnavailable {
    return CommunityUnavailableFromJSONTyped(json, false);
}

export function CommunityUnavailableFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityUnavailable {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
    };
}

export function CommunityUnavailableToJSON(json: any): CommunityUnavailable {
    return CommunityUnavailableToJSONTyped(json, false);
}

export function CommunityUnavailableToJSONTyped(value?: CommunityUnavailable | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
    };
}

