/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunityUnion } from './CommunityUnion';
import {
    CommunityUnionFromJSON,
    CommunityUnionFromJSONTyped,
    CommunityUnionToJSON,
    CommunityUnionToJSONTyped,
} from './CommunityUnion';

/**
 * 
 * @export
 * @interface CommunityResult
 */
export interface CommunityResult {
    /**
     * 
     * @type {CommunityUnion}
     * @memberof CommunityResult
     */
    result: CommunityUnion;
}

/**
 * Check if a given object implements the CommunityResult interface.
 */
export function instanceOfCommunityResult(value: object): value is CommunityResult {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function CommunityResultFromJSON(json: any): CommunityResult {
    return CommunityResultFromJSONTyped(json, false);
}

export function CommunityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityResult {
    if (json == null) {
        return json;
    }
    return {
        
        'result': CommunityUnionFromJSON(json['result']),
    };
}

export function CommunityResultToJSON(json: any): CommunityResult {
    return CommunityResultToJSONTyped(json, false);
}

export function CommunityResultToJSONTyped(value?: CommunityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': CommunityUnionToJSON(value['result']),
    };
}

