/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentDisclosureAdvertisingDisclosure
 */
export interface ContentDisclosureAdvertisingDisclosure {
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisclosureAdvertisingDisclosure
     */
    isPaidPromotion: boolean;
}

/**
 * Check if a given object implements the ContentDisclosureAdvertisingDisclosure interface.
 */
export function instanceOfContentDisclosureAdvertisingDisclosure(value: object): value is ContentDisclosureAdvertisingDisclosure {
    if (!('isPaidPromotion' in value) || value['isPaidPromotion'] === undefined) return false;
    return true;
}

export function ContentDisclosureAdvertisingDisclosureFromJSON(json: any): ContentDisclosureAdvertisingDisclosure {
    return ContentDisclosureAdvertisingDisclosureFromJSONTyped(json, false);
}

export function ContentDisclosureAdvertisingDisclosureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentDisclosureAdvertisingDisclosure {
    if (json == null) {
        return json;
    }
    return {
        
        'isPaidPromotion': json['is_paid_promotion'],
    };
}

export function ContentDisclosureAdvertisingDisclosureToJSON(json: any): ContentDisclosureAdvertisingDisclosure {
    return ContentDisclosureAdvertisingDisclosureToJSONTyped(json, false);
}

export function ContentDisclosureAdvertisingDisclosureToJSONTyped(value?: ContentDisclosureAdvertisingDisclosure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_paid_promotion': value['isPaidPromotion'],
    };
}

