/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentDisclosureAdvertisingDisclosure } from './ContentDisclosureAdvertisingDisclosure';
import {
    ContentDisclosureAdvertisingDisclosureFromJSON,
    ContentDisclosureAdvertisingDisclosureFromJSONTyped,
    ContentDisclosureAdvertisingDisclosureToJSON,
    ContentDisclosureAdvertisingDisclosureToJSONTyped,
} from './ContentDisclosureAdvertisingDisclosure';
import type { ContentDisclosureAiGeneratedDisclosure } from './ContentDisclosureAiGeneratedDisclosure';
import {
    ContentDisclosureAiGeneratedDisclosureFromJSON,
    ContentDisclosureAiGeneratedDisclosureFromJSONTyped,
    ContentDisclosureAiGeneratedDisclosureToJSON,
    ContentDisclosureAiGeneratedDisclosureToJSONTyped,
} from './ContentDisclosureAiGeneratedDisclosure';

/**
 * 
 * @export
 * @interface ContentDisclosure
 */
export interface ContentDisclosure {
    /**
     * 
     * @type {ContentDisclosureAdvertisingDisclosure}
     * @memberof ContentDisclosure
     */
    advertisingDisclosure?: ContentDisclosureAdvertisingDisclosure;
    /**
     * 
     * @type {ContentDisclosureAiGeneratedDisclosure}
     * @memberof ContentDisclosure
     */
    aiGeneratedDisclosure?: ContentDisclosureAiGeneratedDisclosure;
}

/**
 * Check if a given object implements the ContentDisclosure interface.
 */
export function instanceOfContentDisclosure(value: object): value is ContentDisclosure {
    return true;
}

export function ContentDisclosureFromJSON(json: any): ContentDisclosure {
    return ContentDisclosureFromJSONTyped(json, false);
}

export function ContentDisclosureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentDisclosure {
    if (json == null) {
        return json;
    }
    return {
        
        'advertisingDisclosure': json['advertising_disclosure'] == null ? undefined : ContentDisclosureAdvertisingDisclosureFromJSON(json['advertising_disclosure']),
        'aiGeneratedDisclosure': json['ai_generated_disclosure'] == null ? undefined : ContentDisclosureAiGeneratedDisclosureFromJSON(json['ai_generated_disclosure']),
    };
}

export function ContentDisclosureToJSON(json: any): ContentDisclosure {
    return ContentDisclosureToJSONTyped(json, false);
}

export function ContentDisclosureToJSONTyped(value?: ContentDisclosure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'advertising_disclosure': ContentDisclosureAdvertisingDisclosureToJSON(value['advertisingDisclosure']),
        'ai_generated_disclosure': ContentDisclosureAiGeneratedDisclosureToJSON(value['aiGeneratedDisclosure']),
    };
}

