/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentDisclosureAiGeneratedDisclosure
 */
export interface ContentDisclosureAiGeneratedDisclosure {
    /**
     * 
     * @type {ContentDisclosureAiGeneratedDisclosureAiGeneratedDetectionSourceEnum}
     * @memberof ContentDisclosureAiGeneratedDisclosure
     */
    aiGeneratedDetectionSource?: ContentDisclosureAiGeneratedDisclosureAiGeneratedDetectionSourceEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisclosureAiGeneratedDisclosure
     */
    canEdit: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ContentDisclosureAiGeneratedDisclosure
     */
    hasAiGeneratedMedia: boolean;
}


/**
 * @export
 */
export const ContentDisclosureAiGeneratedDisclosureAiGeneratedDetectionSourceEnum = {
    C2paClient: 'C2paClient',
    ContentDisclosureAiGeneratedDisclosure: 'ContentDisclosureAiGeneratedDisclosure',
    UserDeclared: 'UserDeclared'
} as const;
export type ContentDisclosureAiGeneratedDisclosureAiGeneratedDetectionSourceEnum = typeof ContentDisclosureAiGeneratedDisclosureAiGeneratedDetectionSourceEnum[keyof typeof ContentDisclosureAiGeneratedDisclosureAiGeneratedDetectionSourceEnum];


/**
 * Check if a given object implements the ContentDisclosureAiGeneratedDisclosure interface.
 */
export function instanceOfContentDisclosureAiGeneratedDisclosure(value: object): value is ContentDisclosureAiGeneratedDisclosure {
    if (!('canEdit' in value) || value['canEdit'] === undefined) return false;
    if (!('hasAiGeneratedMedia' in value) || value['hasAiGeneratedMedia'] === undefined) return false;
    return true;
}

export function ContentDisclosureAiGeneratedDisclosureFromJSON(json: any): ContentDisclosureAiGeneratedDisclosure {
    return ContentDisclosureAiGeneratedDisclosureFromJSONTyped(json, false);
}

export function ContentDisclosureAiGeneratedDisclosureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentDisclosureAiGeneratedDisclosure {
    if (json == null) {
        return json;
    }
    return {
        
        'aiGeneratedDetectionSource': json['ai_generated_detection_source'] == null ? undefined : json['ai_generated_detection_source'],
        'canEdit': json['can_edit'],
        'hasAiGeneratedMedia': json['has_ai_generated_media'],
    };
}

export function ContentDisclosureAiGeneratedDisclosureToJSON(json: any): ContentDisclosureAiGeneratedDisclosure {
    return ContentDisclosureAiGeneratedDisclosureToJSONTyped(json, false);
}

export function ContentDisclosureAiGeneratedDisclosureToJSONTyped(value?: ContentDisclosureAiGeneratedDisclosure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ai_generated_detection_source': value['aiGeneratedDetectionSource'],
        'can_edit': value['canEdit'],
        'has_ai_generated_media': value['hasAiGeneratedMedia'],
    };
}

