/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Media } from './Media';
import {
    MediaFromJSON,
    MediaFromJSONTyped,
    MediaToJSON,
    MediaToJSONTyped,
} from './Media';
import type { Smarttag } from './Smarttag';
import {
    SmarttagFromJSON,
    SmarttagFromJSONTyped,
    SmarttagToJSON,
    SmarttagToJSONTyped,
} from './Smarttag';
import type { Timestamp } from './Timestamp';
import {
    TimestampFromJSON,
    TimestampFromJSONTyped,
    TimestampToJSON,
    TimestampToJSONTyped,
} from './Timestamp';
import type { Url } from './Url';
import {
    UrlFromJSON,
    UrlFromJSONTyped,
    UrlToJSON,
    UrlToJSONTyped,
} from './Url';

/**
 * 
 * @export
 * @interface Entities
 */
export interface Entities {
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof Entities
     */
    hashtags?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<Media>}
     * @memberof Entities
     */
    media?: Array<Media>;
    /**
     * 
     * @type {Array<Smarttag>}
     * @memberof Entities
     */
    smarttags?: Array<Smarttag>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof Entities
     */
    symbols?: Array<{ [key: string]: any; }>;
    /**
     * 
     * @type {Array<Timestamp>}
     * @memberof Entities
     */
    timestamps?: Array<Timestamp>;
    /**
     * 
     * @type {Array<Url>}
     * @memberof Entities
     */
    urls?: Array<Url>;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof Entities
     */
    userMentions?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the Entities interface.
 */
export function instanceOfEntities(value: object): value is Entities {
    return true;
}

export function EntitiesFromJSON(json: any): Entities {
    return EntitiesFromJSONTyped(json, false);
}

export function EntitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entities {
    if (json == null) {
        return json;
    }
    return {
        
        'hashtags': json['hashtags'] == null ? undefined : json['hashtags'],
        'media': json['media'] == null ? undefined : ((json['media'] as Array<any>).map(MediaFromJSON)),
        'smarttags': json['smarttags'] == null ? undefined : ((json['smarttags'] as Array<any>).map(SmarttagFromJSON)),
        'symbols': json['symbols'] == null ? undefined : json['symbols'],
        'timestamps': json['timestamps'] == null ? undefined : ((json['timestamps'] as Array<any>).map(TimestampFromJSON)),
        'urls': json['urls'] == null ? undefined : ((json['urls'] as Array<any>).map(UrlFromJSON)),
        'userMentions': json['user_mentions'] == null ? undefined : json['user_mentions'],
    };
}

export function EntitiesToJSON(json: any): Entities {
    return EntitiesToJSONTyped(json, false);
}

export function EntitiesToJSONTyped(value?: Entities | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hashtags': value['hashtags'],
        'media': value['media'] == null ? undefined : ((value['media'] as Array<any>).map(MediaToJSON)),
        'smarttags': value['smarttags'] == null ? undefined : ((value['smarttags'] as Array<any>).map(SmarttagToJSON)),
        'symbols': value['symbols'],
        'timestamps': value['timestamps'] == null ? undefined : ((value['timestamps'] as Array<any>).map(TimestampToJSON)),
        'urls': value['urls'] == null ? undefined : ((value['urls'] as Array<any>).map(UrlToJSON)),
        'user_mentions': value['userMentions'],
    };
}

