/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ErrorResponsePathInner
 * 
 * @export
 */
export type ErrorResponsePathInner = number | string;

export function ErrorResponsePathInnerFromJSON(json: any): ErrorResponsePathInner {
    return ErrorResponsePathInnerFromJSONTyped(json, false);
}

export function ErrorResponsePathInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponsePathInner {
    if (json == null) {
        return json;
    }
    if (typeof json === 'string') {
        return json;
    }
    if (typeof json === 'number') {
        return json;
    }
    return {} as any;
}

export function ErrorResponsePathInnerToJSON(json: any): any {
    return ErrorResponsePathInnerToJSONTyped(json, false);
}

export function ErrorResponsePathInnerToJSONTyped(value?: ErrorResponsePathInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value === 'string') {
        return value;
    }
    if (typeof value === 'number') {
        return value;
    }
    return {};
}

