/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrokTranslatedCommunityNote } from './GrokTranslatedCommunityNote';
import {
    GrokTranslatedCommunityNoteFromJSON,
    GrokTranslatedCommunityNoteFromJSONTyped,
    GrokTranslatedCommunityNoteToJSON,
    GrokTranslatedCommunityNoteToJSONTyped,
} from './GrokTranslatedCommunityNote';

/**
 * 
 * @export
 * @interface GrokTranslatedCommunityNoteWithAvailability
 */
export interface GrokTranslatedCommunityNoteWithAvailability {
    /**
     * 
     * @type {GrokTranslatedCommunityNote}
     * @memberof GrokTranslatedCommunityNoteWithAvailability
     */
    data?: GrokTranslatedCommunityNote;
    /**
     * 
     * @type {boolean}
     * @memberof GrokTranslatedCommunityNoteWithAvailability
     */
    isAvailable: boolean;
}

/**
 * Check if a given object implements the GrokTranslatedCommunityNoteWithAvailability interface.
 */
export function instanceOfGrokTranslatedCommunityNoteWithAvailability(value: object): value is GrokTranslatedCommunityNoteWithAvailability {
    if (!('isAvailable' in value) || value['isAvailable'] === undefined) return false;
    return true;
}

export function GrokTranslatedCommunityNoteWithAvailabilityFromJSON(json: any): GrokTranslatedCommunityNoteWithAvailability {
    return GrokTranslatedCommunityNoteWithAvailabilityFromJSONTyped(json, false);
}

export function GrokTranslatedCommunityNoteWithAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokTranslatedCommunityNoteWithAvailability {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : GrokTranslatedCommunityNoteFromJSON(json['data']),
        'isAvailable': json['is_available'],
    };
}

export function GrokTranslatedCommunityNoteWithAvailabilityToJSON(json: any): GrokTranslatedCommunityNoteWithAvailability {
    return GrokTranslatedCommunityNoteWithAvailabilityToJSONTyped(json, false);
}

export function GrokTranslatedCommunityNoteWithAvailabilityToJSONTyped(value?: GrokTranslatedCommunityNoteWithAvailability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GrokTranslatedCommunityNoteToJSON(value['data']),
        'is_available': value['isAvailable'],
    };
}

