/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrokTranslatedPost } from './GrokTranslatedPost';
import {
    GrokTranslatedPostFromJSON,
    GrokTranslatedPostFromJSONTyped,
    GrokTranslatedPostToJSON,
    GrokTranslatedPostToJSONTyped,
} from './GrokTranslatedPost';

/**
 * 
 * @export
 * @interface GrokTranslatedPostWithAvailability
 */
export interface GrokTranslatedPostWithAvailability {
    /**
     * 
     * @type {GrokTranslatedPost}
     * @memberof GrokTranslatedPostWithAvailability
     */
    data?: GrokTranslatedPost;
    /**
     * 
     * @type {boolean}
     * @memberof GrokTranslatedPostWithAvailability
     */
    isAvailable: boolean;
}

/**
 * Check if a given object implements the GrokTranslatedPostWithAvailability interface.
 */
export function instanceOfGrokTranslatedPostWithAvailability(value: object): value is GrokTranslatedPostWithAvailability {
    if (!('isAvailable' in value) || value['isAvailable'] === undefined) return false;
    return true;
}

export function GrokTranslatedPostWithAvailabilityFromJSON(json: any): GrokTranslatedPostWithAvailability {
    return GrokTranslatedPostWithAvailabilityFromJSONTyped(json, false);
}

export function GrokTranslatedPostWithAvailabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokTranslatedPostWithAvailability {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : GrokTranslatedPostFromJSON(json['data']),
        'isAvailable': json['is_available'],
    };
}

export function GrokTranslatedPostWithAvailabilityToJSON(json: any): GrokTranslatedPostWithAvailability {
    return GrokTranslatedPostWithAvailabilityToJSONTyped(json, false);
}

export function GrokTranslatedPostWithAvailabilityToJSONTyped(value?: GrokTranslatedPostWithAvailability | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GrokTranslatedPostToJSON(value['data']),
        'is_available': value['isAvailable'],
    };
}

