/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrokEntityRef
 */
export interface GrokEntityRef {
    /**
     * 
     * @type {string}
     * @memberof GrokEntityRef
     */
    displayUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GrokEntityRef
     */
    expandedUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof GrokEntityRef
     */
    text?: string;
    /**
     * 
     * @type {GrokEntityRefTypeEnum}
     * @memberof GrokEntityRef
     */
    type: GrokEntityRefTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GrokEntityRef
     */
    url?: string;
    /**
     * 
     * @type {GrokEntityRefUrlTypeEnum}
     * @memberof GrokEntityRef
     */
    urlType?: GrokEntityRefUrlTypeEnum;
}


/**
 * @export
 */
export const GrokEntityRefTypeEnum = {
    TimelineUrl: 'TimelineUrl',
    TimelineRichTextHashtag: 'TimelineRichTextHashtag'
} as const;
export type GrokEntityRefTypeEnum = typeof GrokEntityRefTypeEnum[keyof typeof GrokEntityRefTypeEnum];

/**
 * @export
 */
export const GrokEntityRefUrlTypeEnum = {
    ExternalUrl: 'ExternalUrl'
} as const;
export type GrokEntityRefUrlTypeEnum = typeof GrokEntityRefUrlTypeEnum[keyof typeof GrokEntityRefUrlTypeEnum];


/**
 * Check if a given object implements the GrokEntityRef interface.
 */
export function instanceOfGrokEntityRef(value: object): value is GrokEntityRef {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GrokEntityRefFromJSON(json: any): GrokEntityRef {
    return GrokEntityRefFromJSONTyped(json, false);
}

export function GrokEntityRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokEntityRef {
    if (json == null) {
        return json;
    }
    return {
        
        'displayUrl': json['display_url'] == null ? undefined : json['display_url'],
        'expandedUrl': json['expanded_url'] == null ? undefined : json['expanded_url'],
        'text': json['text'] == null ? undefined : json['text'],
        'type': json['type'],
        'url': json['url'] == null ? undefined : json['url'],
        'urlType': json['url_type'] == null ? undefined : json['url_type'],
    };
}

export function GrokEntityRefToJSON(json: any): GrokEntityRef {
    return GrokEntityRefToJSONTyped(json, false);
}

export function GrokEntityRefToJSONTyped(value?: GrokEntityRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_url': value['displayUrl'],
        'expanded_url': value['expandedUrl'],
        'text': value['text'],
        'type': value['type'],
        'url': value['url'],
        'url_type': value['urlType'],
    };
}

