/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrokEntityRef } from './GrokEntityRef';
import {
    GrokEntityRefFromJSON,
    GrokEntityRefFromJSONTyped,
    GrokEntityRefToJSON,
    GrokEntityRefToJSONTyped,
} from './GrokEntityRef';

/**
 * 
 * @export
 * @interface GrokEntity
 */
export interface GrokEntity {
    /**
     * 
     * @type {string}
     * @memberof GrokEntity
     */
    fromIndex: string;
    /**
     * 
     * @type {GrokEntityRef}
     * @memberof GrokEntity
     */
    ref: GrokEntityRef;
    /**
     * 
     * @type {string}
     * @memberof GrokEntity
     */
    toIndex: string;
}

/**
 * Check if a given object implements the GrokEntity interface.
 */
export function instanceOfGrokEntity(value: object): value is GrokEntity {
    if (!('fromIndex' in value) || value['fromIndex'] === undefined) return false;
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('toIndex' in value) || value['toIndex'] === undefined) return false;
    return true;
}

export function GrokEntityFromJSON(json: any): GrokEntity {
    return GrokEntityFromJSONTyped(json, false);
}

export function GrokEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'fromIndex': json['from_index'],
        'ref': GrokEntityRefFromJSON(json['ref']),
        'toIndex': json['to_index'],
    };
}

export function GrokEntityToJSON(json: any): GrokEntity {
    return GrokEntityToJSONTyped(json, false);
}

export function GrokEntityToJSONTyped(value?: GrokEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from_index': value['fromIndex'],
        'ref': GrokEntityRefToJSON(value['ref']),
        'to_index': value['toIndex'],
    };
}

