/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Entities } from './Entities';
import {
    EntitiesFromJSON,
    EntitiesFromJSONTyped,
    EntitiesToJSON,
    EntitiesToJSONTyped,
} from './Entities';

/**
 * 
 * @export
 * @interface GrokTranslatedPost
 */
export interface GrokTranslatedPost {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GrokTranslatedPost
     */
    associatedData?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof GrokTranslatedPost
     */
    destinationLanguage?: string;
    /**
     * 
     * @type {Entities}
     * @memberof GrokTranslatedPost
     */
    entities?: Entities;
    /**
     * 
     * @type {string}
     * @memberof GrokTranslatedPost
     */
    previewTranslation?: string;
    /**
     * 
     * @type {string}
     * @memberof GrokTranslatedPost
     */
    sourceLanguage?: string;
    /**
     * 
     * @type {string}
     * @memberof GrokTranslatedPost
     */
    translation?: string;
}

/**
 * Check if a given object implements the GrokTranslatedPost interface.
 */
export function instanceOfGrokTranslatedPost(value: object): value is GrokTranslatedPost {
    return true;
}

export function GrokTranslatedPostFromJSON(json: any): GrokTranslatedPost {
    return GrokTranslatedPostFromJSONTyped(json, false);
}

export function GrokTranslatedPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokTranslatedPost {
    if (json == null) {
        return json;
    }
    return {
        
        'associatedData': json['associated_data'] == null ? undefined : json['associated_data'],
        'destinationLanguage': json['destination_language'] == null ? undefined : json['destination_language'],
        'entities': json['entities'] == null ? undefined : EntitiesFromJSON(json['entities']),
        'previewTranslation': json['preview_translation'] == null ? undefined : json['preview_translation'],
        'sourceLanguage': json['source_language'] == null ? undefined : json['source_language'],
        'translation': json['translation'] == null ? undefined : json['translation'],
    };
}

export function GrokTranslatedPostToJSON(json: any): GrokTranslatedPost {
    return GrokTranslatedPostToJSONTyped(json, false);
}

export function GrokTranslatedPostToJSONTyped(value?: GrokTranslatedPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'associated_data': value['associatedData'],
        'destination_language': value['destinationLanguage'],
        'entities': EntitiesToJSON(value['entities']),
        'preview_translation': value['previewTranslation'],
        'source_language': value['sourceLanguage'],
        'translation': value['translation'],
    };
}

