/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrokAnnotation
 */
export interface GrokAnnotation {
    /**
     * 
     * @type {boolean}
     * @memberof GrokAnnotation
     */
    isImageEditableByGrok?: boolean;
}

/**
 * Check if a given object implements the GrokAnnotation interface.
 */
export function instanceOfGrokAnnotation(value: object): value is GrokAnnotation {
    return true;
}

export function GrokAnnotationFromJSON(json: any): GrokAnnotation {
    return GrokAnnotationFromJSONTyped(json, false);
}

export function GrokAnnotationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokAnnotation {
    if (json == null) {
        return json;
    }
    return {
        
        'isImageEditableByGrok': json['is_image_editable_by_grok'] == null ? undefined : json['is_image_editable_by_grok'],
    };
}

export function GrokAnnotationToJSON(json: any): GrokAnnotation {
    return GrokAnnotationToJSONTyped(json, false);
}

export function GrokAnnotationToJSONTyped(value?: GrokAnnotation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_image_editable_by_grok': value['isImageEditableByGrok'],
    };
}

