/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GrokEntity } from './GrokEntity';
import {
    GrokEntityFromJSON,
    GrokEntityFromJSONTyped,
    GrokEntityToJSON,
    GrokEntityToJSONTyped,
} from './GrokEntity';

/**
 * 
 * @export
 * @interface GrokTranslatedCommunityNote
 */
export interface GrokTranslatedCommunityNote {
    /**
     * 
     * @type {string}
     * @memberof GrokTranslatedCommunityNote
     */
    destinationLanguage: string;
    /**
     * 
     * @type {Array<GrokEntity>}
     * @memberof GrokTranslatedCommunityNote
     */
    richTextEntities?: Array<GrokEntity>;
    /**
     * 
     * @type {string}
     * @memberof GrokTranslatedCommunityNote
     */
    sourceLanguage: string;
    /**
     * 
     * @type {string}
     * @memberof GrokTranslatedCommunityNote
     */
    translation: string;
    /**
     * 
     * @type {boolean}
     * @memberof GrokTranslatedCommunityNote
     */
    translationAvailable: boolean;
}

/**
 * Check if a given object implements the GrokTranslatedCommunityNote interface.
 */
export function instanceOfGrokTranslatedCommunityNote(value: object): value is GrokTranslatedCommunityNote {
    if (!('destinationLanguage' in value) || value['destinationLanguage'] === undefined) return false;
    if (!('sourceLanguage' in value) || value['sourceLanguage'] === undefined) return false;
    if (!('translation' in value) || value['translation'] === undefined) return false;
    if (!('translationAvailable' in value) || value['translationAvailable'] === undefined) return false;
    return true;
}

export function GrokTranslatedCommunityNoteFromJSON(json: any): GrokTranslatedCommunityNote {
    return GrokTranslatedCommunityNoteFromJSONTyped(json, false);
}

export function GrokTranslatedCommunityNoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrokTranslatedCommunityNote {
    if (json == null) {
        return json;
    }
    return {
        
        'destinationLanguage': json['destination_language'],
        'richTextEntities': json['rich_text_entities'] == null ? undefined : ((json['rich_text_entities'] as Array<any>).map(GrokEntityFromJSON)),
        'sourceLanguage': json['source_language'],
        'translation': json['translation'],
        'translationAvailable': json['translation_available'],
    };
}

export function GrokTranslatedCommunityNoteToJSON(json: any): GrokTranslatedCommunityNote {
    return GrokTranslatedCommunityNoteToJSONTyped(json, false);
}

export function GrokTranslatedCommunityNoteToJSONTyped(value?: GrokTranslatedCommunityNote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'destination_language': value['destinationLanguage'],
        'rich_text_entities': value['richTextEntities'] == null ? undefined : ((value['richTextEntities'] as Array<any>).map(GrokEntityToJSON)),
        'source_language': value['sourceLanguage'],
        'translation': value['translation'],
        'translation_available': value['translationAvailable'],
    };
}

