/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';
import type { PostCtaUserResultsAvatar } from './PostCtaUserResultsAvatar';
import {
    PostCtaUserResultsAvatarFromJSON,
    PostCtaUserResultsAvatarFromJSONTyped,
    PostCtaUserResultsAvatarToJSON,
    PostCtaUserResultsAvatarToJSONTyped,
} from './PostCtaUserResultsAvatar';

/**
 * 
 * @export
 * @interface PostCtaUserResultsResult
 */
export interface PostCtaUserResultsResult {
    /**
     * 
     * @type {TypeName}
     * @memberof PostCtaUserResultsResult
     */
    typename: TypeName;
    /**
     * 
     * @type {PostCtaUserResultsAvatar}
     * @memberof PostCtaUserResultsResult
     */
    avatar: PostCtaUserResultsAvatar;
}



/**
 * Check if a given object implements the PostCtaUserResultsResult interface.
 */
export function instanceOfPostCtaUserResultsResult(value: object): value is PostCtaUserResultsResult {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    if (!('avatar' in value) || value['avatar'] === undefined) return false;
    return true;
}

export function PostCtaUserResultsResultFromJSON(json: any): PostCtaUserResultsResult {
    return PostCtaUserResultsResultFromJSONTyped(json, false);
}

export function PostCtaUserResultsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCtaUserResultsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'avatar': PostCtaUserResultsAvatarFromJSON(json['avatar']),
    };
}

export function PostCtaUserResultsResultToJSON(json: any): PostCtaUserResultsResult {
    return PostCtaUserResultsResultToJSONTyped(json, false);
}

export function PostCtaUserResultsResultToJSONTyped(value?: PostCtaUserResultsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
        'avatar': PostCtaUserResultsAvatarToJSON(value['avatar']),
    };
}

