/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCtaUserResultsAvatar
 */
export interface PostCtaUserResultsAvatar {
    /**
     * 
     * @type {string}
     * @memberof PostCtaUserResultsAvatar
     */
    imageUrl: string;
}

/**
 * Check if a given object implements the PostCtaUserResultsAvatar interface.
 */
export function instanceOfPostCtaUserResultsAvatar(value: object): value is PostCtaUserResultsAvatar {
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function PostCtaUserResultsAvatarFromJSON(json: any): PostCtaUserResultsAvatar {
    return PostCtaUserResultsAvatarFromJSONTyped(json, false);
}

export function PostCtaUserResultsAvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCtaUserResultsAvatar {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['image_url'],
    };
}

export function PostCtaUserResultsAvatarToJSON(json: any): PostCtaUserResultsAvatar {
    return PostCtaUserResultsAvatarToJSONTyped(json, false);
}

export function PostCtaUserResultsAvatarToJSONTyped(value?: PostCtaUserResultsAvatar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_url': value['imageUrl'],
    };
}

