/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCtaTitleTextEntityRef } from './PostCtaTitleTextEntityRef';
import {
    PostCtaTitleTextEntityRefFromJSON,
    PostCtaTitleTextEntityRefFromJSONTyped,
    PostCtaTitleTextEntityRefToJSON,
    PostCtaTitleTextEntityRefToJSONTyped,
} from './PostCtaTitleTextEntityRef';

/**
 * 
 * @export
 * @interface PostCtaTitleTextEntity
 */
export interface PostCtaTitleTextEntity {
    /**
     * 
     * @type {number}
     * @memberof PostCtaTitleTextEntity
     */
    fromIndex: number;
    /**
     * 
     * @type {PostCtaTitleTextEntityRef}
     * @memberof PostCtaTitleTextEntity
     */
    ref: PostCtaTitleTextEntityRef;
    /**
     * 
     * @type {number}
     * @memberof PostCtaTitleTextEntity
     */
    toIndex: number;
}

/**
 * Check if a given object implements the PostCtaTitleTextEntity interface.
 */
export function instanceOfPostCtaTitleTextEntity(value: object): value is PostCtaTitleTextEntity {
    if (!('fromIndex' in value) || value['fromIndex'] === undefined) return false;
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('toIndex' in value) || value['toIndex'] === undefined) return false;
    return true;
}

export function PostCtaTitleTextEntityFromJSON(json: any): PostCtaTitleTextEntity {
    return PostCtaTitleTextEntityFromJSONTyped(json, false);
}

export function PostCtaTitleTextEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCtaTitleTextEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'fromIndex': json['fromIndex'],
        'ref': PostCtaTitleTextEntityRefFromJSON(json['ref']),
        'toIndex': json['toIndex'],
    };
}

export function PostCtaTitleTextEntityToJSON(json: any): PostCtaTitleTextEntity {
    return PostCtaTitleTextEntityToJSONTyped(json, false);
}

export function PostCtaTitleTextEntityToJSONTyped(value?: PostCtaTitleTextEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fromIndex': value['fromIndex'],
        'ref': PostCtaTitleTextEntityRefToJSON(value['ref']),
        'toIndex': value['toIndex'],
    };
}

