/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCtaTitleText } from './PostCtaTitleText';
import {
    PostCtaTitleTextFromJSON,
    PostCtaTitleTextFromJSONTyped,
    PostCtaTitleTextToJSON,
    PostCtaTitleTextToJSONTyped,
} from './PostCtaTitleText';

/**
 * 
 * @export
 * @interface PostCta
 */
export interface PostCta {
    /**
     * 
     * @type {string}
     * @memberof PostCta
     */
    actionUrl: string;
    /**
     * 
     * @type {string}
     * @memberof PostCta
     */
    backgroundColor: string;
    /**
     * 
     * @type {boolean}
     * @memberof PostCta
     */
    showChevron: boolean;
    /**
     * 
     * @type {string}
     * @memberof PostCta
     */
    strokeColor: string;
    /**
     * 
     * @type {PostCtaTitleText}
     * @memberof PostCta
     */
    titleText: PostCtaTitleText;
}

/**
 * Check if a given object implements the PostCta interface.
 */
export function instanceOfPostCta(value: object): value is PostCta {
    if (!('actionUrl' in value) || value['actionUrl'] === undefined) return false;
    if (!('backgroundColor' in value) || value['backgroundColor'] === undefined) return false;
    if (!('showChevron' in value) || value['showChevron'] === undefined) return false;
    if (!('strokeColor' in value) || value['strokeColor'] === undefined) return false;
    if (!('titleText' in value) || value['titleText'] === undefined) return false;
    return true;
}

export function PostCtaFromJSON(json: any): PostCta {
    return PostCtaFromJSONTyped(json, false);
}

export function PostCtaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCta {
    if (json == null) {
        return json;
    }
    return {
        
        'actionUrl': json['action_url'],
        'backgroundColor': json['background_color'],
        'showChevron': json['show_chevron'],
        'strokeColor': json['stroke_color'],
        'titleText': PostCtaTitleTextFromJSON(json['title_text']),
    };
}

export function PostCtaToJSON(json: any): PostCta {
    return PostCtaToJSONTyped(json, false);
}

export function PostCtaToJSONTyped(value?: PostCta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action_url': value['actionUrl'],
        'background_color': value['backgroundColor'],
        'show_chevron': value['showChevron'],
        'stroke_color': value['strokeColor'],
        'title_text': PostCtaTitleTextToJSON(value['titleText']),
    };
}

