/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCtaUserResultsResult } from './PostCtaUserResultsResult';
import {
    PostCtaUserResultsResultFromJSON,
    PostCtaUserResultsResultFromJSONTyped,
    PostCtaUserResultsResultToJSON,
    PostCtaUserResultsResultToJSONTyped,
} from './PostCtaUserResultsResult';

/**
 * 
 * @export
 * @interface PostCtaUserResults
 */
export interface PostCtaUserResults {
    /**
     * 
     * @type {PostCtaUserResultsResult}
     * @memberof PostCtaUserResults
     */
    result: PostCtaUserResultsResult;
}

/**
 * Check if a given object implements the PostCtaUserResults interface.
 */
export function instanceOfPostCtaUserResults(value: object): value is PostCtaUserResults {
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function PostCtaUserResultsFromJSON(json: any): PostCtaUserResults {
    return PostCtaUserResultsFromJSONTyped(json, false);
}

export function PostCtaUserResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCtaUserResults {
    if (json == null) {
        return json;
    }
    return {
        
        'result': PostCtaUserResultsResultFromJSON(json['result']),
    };
}

export function PostCtaUserResultsToJSON(json: any): PostCtaUserResults {
    return PostCtaUserResultsToJSONTyped(json, false);
}

export function PostCtaUserResultsToJSONTyped(value?: PostCtaUserResults | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': PostCtaUserResultsResultToJSON(value['result']),
    };
}

