/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCtaTitleTextEntity } from './PostCtaTitleTextEntity';
import {
    PostCtaTitleTextEntityFromJSON,
    PostCtaTitleTextEntityFromJSONTyped,
    PostCtaTitleTextEntityToJSON,
    PostCtaTitleTextEntityToJSONTyped,
} from './PostCtaTitleTextEntity';

/**
 * 
 * @export
 * @interface PostCtaTitleText
 */
export interface PostCtaTitleText {
    /**
     * 
     * @type {Array<PostCtaTitleTextEntity>}
     * @memberof PostCtaTitleText
     */
    entities: Array<PostCtaTitleTextEntity>;
    /**
     * 
     * @type {string}
     * @memberof PostCtaTitleText
     */
    text: string;
}

/**
 * Check if a given object implements the PostCtaTitleText interface.
 */
export function instanceOfPostCtaTitleText(value: object): value is PostCtaTitleText {
    if (!('entities' in value) || value['entities'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PostCtaTitleTextFromJSON(json: any): PostCtaTitleText {
    return PostCtaTitleTextFromJSONTyped(json, false);
}

export function PostCtaTitleTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCtaTitleText {
    if (json == null) {
        return json;
    }
    return {
        
        'entities': ((json['entities'] as Array<any>).map(PostCtaTitleTextEntityFromJSON)),
        'text': json['text'],
    };
}

export function PostCtaTitleTextToJSON(json: any): PostCtaTitleText {
    return PostCtaTitleTextToJSONTyped(json, false);
}

export function PostCtaTitleTextToJSONTyped(value?: PostCtaTitleText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entities': ((value['entities'] as Array<any>).map(PostCtaTitleTextEntityToJSON)),
        'text': value['text'],
    };
}

