/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';
import type { PostCtaUserResults } from './PostCtaUserResults';
import {
    PostCtaUserResultsFromJSON,
    PostCtaUserResultsFromJSONTyped,
    PostCtaUserResultsToJSON,
    PostCtaUserResultsToJSONTyped,
} from './PostCtaUserResults';

/**
 * 
 * @export
 * @interface PostCtaTitleTextEntityRef
 */
export interface PostCtaTitleTextEntityRef {
    /**
     * 
     * @type {TypeName}
     * @memberof PostCtaTitleTextEntityRef
     */
    typename: TypeName;
    /**
     * 
     * @type {PostCtaUserResults}
     * @memberof PostCtaTitleTextEntityRef
     */
    userResults?: PostCtaUserResults;
}



/**
 * Check if a given object implements the PostCtaTitleTextEntityRef interface.
 */
export function instanceOfPostCtaTitleTextEntityRef(value: object): value is PostCtaTitleTextEntityRef {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    return true;
}

export function PostCtaTitleTextEntityRefFromJSON(json: any): PostCtaTitleTextEntityRef {
    return PostCtaTitleTextEntityRefFromJSONTyped(json, false);
}

export function PostCtaTitleTextEntityRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCtaTitleTextEntityRef {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'userResults': json['user_results'] == null ? undefined : PostCtaUserResultsFromJSON(json['user_results']),
    };
}

export function PostCtaTitleTextEntityRefToJSON(json: any): PostCtaTitleTextEntityRef {
    return PostCtaTitleTextEntityRefToJSONTyped(json, false);
}

export function PostCtaTitleTextEntityRefToJSONTyped(value?: PostCtaTitleTextEntityRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
        'user_results': PostCtaUserResultsToJSON(value['userResults']),
    };
}

