/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileBio
 */
export interface ProfileBio {
    /**
     * 
     * @type {string}
     * @memberof ProfileBio
     */
    description: string;
}

/**
 * Check if a given object implements the ProfileBio interface.
 */
export function instanceOfProfileBio(value: object): value is ProfileBio {
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function ProfileBioFromJSON(json: any): ProfileBio {
    return ProfileBioFromJSONTyped(json, false);
}

export function ProfileBioFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileBio {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
    };
}

export function ProfileBioToJSON(json: any): ProfileBio {
    return ProfileBioToJSONTyped(json, false);
}

export function ProfileBioToJSONTyped(value?: ProfileBio | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
    };
}

