/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SmarttagTag } from './SmarttagTag';
import {
    SmarttagTagFromJSON,
    SmarttagTagFromJSONTyped,
    SmarttagTagToJSON,
    SmarttagTagToJSONTyped,
} from './SmarttagTag';

/**
 * 
 * @export
 * @interface Smarttag
 */
export interface Smarttag {
    /**
     * 
     * @type {Array<number>}
     * @memberof Smarttag
     */
    indices: Array<number>;
    /**
     * 
     * @type {SmarttagTag}
     * @memberof Smarttag
     */
    tag: SmarttagTag;
    /**
     * 
     * @type {string}
     * @memberof Smarttag
     */
    text: string;
}

/**
 * Check if a given object implements the Smarttag interface.
 */
export function instanceOfSmarttag(value: object): value is Smarttag {
    if (!('indices' in value) || value['indices'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function SmarttagFromJSON(json: any): Smarttag {
    return SmarttagFromJSONTyped(json, false);
}

export function SmarttagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Smarttag {
    if (json == null) {
        return json;
    }
    return {
        
        'indices': json['indices'],
        'tag': SmarttagTagFromJSON(json['tag']),
        'text': json['text'],
    };
}

export function SmarttagToJSON(json: any): Smarttag {
    return SmarttagToJSONTyped(json, false);
}

export function SmarttagToJSONTyped(value?: Smarttag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'indices': value['indices'],
        'tag': SmarttagTagToJSON(value['tag']),
        'text': value['text'],
    };
}

