/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SmarttagTag
 */
export interface SmarttagTag {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SmarttagTag
     */
    info: { [key: string]: any; };
}

/**
 * Check if a given object implements the SmarttagTag interface.
 */
export function instanceOfSmarttagTag(value: object): value is SmarttagTag {
    if (!('info' in value) || value['info'] === undefined) return false;
    return true;
}

export function SmarttagTagFromJSON(json: any): SmarttagTag {
    return SmarttagTagFromJSONTyped(json, false);
}

export function SmarttagTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): SmarttagTag {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'],
    };
}

export function SmarttagTagToJSON(json: any): SmarttagTag {
    return SmarttagTagToJSONTyped(json, false);
}

export function SmarttagTagToJSONTyped(value?: SmarttagTag | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': value['info'],
    };
}

