/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuperFollowUserProfile
 */
export interface SuperFollowUserProfile {
    /**
     * 
     * @type {boolean}
     * @memberof SuperFollowUserProfile
     */
    isActive: boolean;
}

/**
 * Check if a given object implements the SuperFollowUserProfile interface.
 */
export function instanceOfSuperFollowUserProfile(value: object): value is SuperFollowUserProfile {
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    return true;
}

export function SuperFollowUserProfileFromJSON(json: any): SuperFollowUserProfile {
    return SuperFollowUserProfileFromJSONTyped(json, false);
}

export function SuperFollowUserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuperFollowUserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'isActive': json['is_active'],
    };
}

export function SuperFollowUserProfileToJSON(json: any): SuperFollowUserProfile {
    return SuperFollowUserProfileToJSONTyped(json, false);
}

export function SuperFollowUserProfileToJSONTyped(value?: SuperFollowUserProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_active': value['isActive'],
    };
}

