/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SuperFollowsReplyUserResultCore
 */
export interface SuperFollowsReplyUserResultCore {
    /**
     * 
     * @type {string}
     * @memberof SuperFollowsReplyUserResultCore
     */
    screenName: string;
}

/**
 * Check if a given object implements the SuperFollowsReplyUserResultCore interface.
 */
export function instanceOfSuperFollowsReplyUserResultCore(value: object): value is SuperFollowsReplyUserResultCore {
    if (!('screenName' in value) || value['screenName'] === undefined) return false;
    return true;
}

export function SuperFollowsReplyUserResultCoreFromJSON(json: any): SuperFollowsReplyUserResultCore {
    return SuperFollowsReplyUserResultCoreFromJSONTyped(json, false);
}

export function SuperFollowsReplyUserResultCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): SuperFollowsReplyUserResultCore {
    if (json == null) {
        return json;
    }
    return {
        
        'screenName': json['screen_name'],
    };
}

export function SuperFollowsReplyUserResultCoreToJSON(json: any): SuperFollowsReplyUserResultCore {
    return SuperFollowsReplyUserResultCoreToJSONTyped(json, false);
}

export function SuperFollowsReplyUserResultCoreToJSONTyped(value?: SuperFollowsReplyUserResultCore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'screen_name': value['screenName'],
    };
}

