/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostCta } from './PostCta';
import {
    PostCtaFromJSON,
    PostCtaFromJSONTyped,
    PostCtaToJSON,
    PostCtaToJSONTyped,
} from './PostCta';

/**
 * 
 * @export
 * @interface TweetPostCta
 */
export interface TweetPostCta {
    /**
     * 
     * @type {Array<TweetPostCtaDisplayLocationsEnum>}
     * @memberof TweetPostCta
     */
    displayLocations: Array<TweetPostCtaDisplayLocationsEnum>;
    /**
     * 
     * @type {PostCta}
     * @memberof TweetPostCta
     */
    postCta: PostCta;
    /**
     * 
     * @type {string}
     * @memberof TweetPostCta
     */
    scribeId?: string;
}


/**
 * @export
 */
export const TweetPostCtaDisplayLocationsEnum = {
    TweetDetails: 'TweetDetails',
    ForYouTimeline: 'ForYouTimeline',
    RepliesTimeline: 'RepliesTimeline'
} as const;
export type TweetPostCtaDisplayLocationsEnum = typeof TweetPostCtaDisplayLocationsEnum[keyof typeof TweetPostCtaDisplayLocationsEnum];


/**
 * Check if a given object implements the TweetPostCta interface.
 */
export function instanceOfTweetPostCta(value: object): value is TweetPostCta {
    if (!('displayLocations' in value) || value['displayLocations'] === undefined) return false;
    if (!('postCta' in value) || value['postCta'] === undefined) return false;
    return true;
}

export function TweetPostCtaFromJSON(json: any): TweetPostCta {
    return TweetPostCtaFromJSONTyped(json, false);
}

export function TweetPostCtaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TweetPostCta {
    if (json == null) {
        return json;
    }
    return {
        
        'displayLocations': json['display_locations'],
        'postCta': PostCtaFromJSON(json['post_cta']),
        'scribeId': json['scribe_id'] == null ? undefined : json['scribe_id'],
    };
}

export function TweetPostCtaToJSON(json: any): TweetPostCta {
    return TweetPostCtaToJSONTyped(json, false);
}

export function TweetPostCtaToJSONTyped(value?: TweetPostCta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_locations': value['displayLocations'],
        'post_cta': PostCtaToJSON(value['postCta']),
        'scribe_id': value['scribeId'],
    };
}

