/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResultPrivacy
 */
export interface UserResultPrivacy {
    /**
     * 
     * @type {boolean}
     * @memberof UserResultPrivacy
     */
    _protected: boolean;
}

/**
 * Check if a given object implements the UserResultPrivacy interface.
 */
export function instanceOfUserResultPrivacy(value: object): value is UserResultPrivacy {
    if (!('_protected' in value) || value['_protected'] === undefined) return false;
    return true;
}

export function UserResultPrivacyFromJSON(json: any): UserResultPrivacy {
    return UserResultPrivacyFromJSONTyped(json, false);
}

export function UserResultPrivacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResultPrivacy {
    if (json == null) {
        return json;
    }
    return {
        
        '_protected': json['protected'],
    };
}

export function UserResultPrivacyToJSON(json: any): UserResultPrivacy {
    return UserResultPrivacyToJSONTyped(json, false);
}

export function UserResultPrivacyToJSONTyped(value?: UserResultPrivacy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protected': value['_protected'],
    };
}

