/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResultByScreenNameCore
 */
export interface UserResultByScreenNameCore {
    /**
     * 
     * @type {string}
     * @memberof UserResultByScreenNameCore
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserResultByScreenNameCore
     */
    screenName: string;
}

/**
 * Check if a given object implements the UserResultByScreenNameCore interface.
 */
export function instanceOfUserResultByScreenNameCore(value: object): value is UserResultByScreenNameCore {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('screenName' in value) || value['screenName'] === undefined) return false;
    return true;
}

export function UserResultByScreenNameCoreFromJSON(json: any): UserResultByScreenNameCore {
    return UserResultByScreenNameCoreFromJSONTyped(json, false);
}

export function UserResultByScreenNameCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResultByScreenNameCore {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'screenName': json['screen_name'],
    };
}

export function UserResultByScreenNameCoreToJSON(json: any): UserResultByScreenNameCore {
    return UserResultByScreenNameCoreToJSONTyped(json, false);
}

export function UserResultByScreenNameCoreToJSONTyped(value?: UserResultByScreenNameCore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'screen_name': value['screenName'],
    };
}

