/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDmPermissions
 */
export interface UserDmPermissions {
    /**
     * 
     * @type {boolean}
     * @memberof UserDmPermissions
     */
    canDm: boolean;
}

/**
 * Check if a given object implements the UserDmPermissions interface.
 */
export function instanceOfUserDmPermissions(value: object): value is UserDmPermissions {
    if (!('canDm' in value) || value['canDm'] === undefined) return false;
    return true;
}

export function UserDmPermissionsFromJSON(json: any): UserDmPermissions {
    return UserDmPermissionsFromJSONTyped(json, false);
}

export function UserDmPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDmPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'canDm': json['can_dm'],
    };
}

export function UserDmPermissionsToJSON(json: any): UserDmPermissions {
    return UserDmPermissionsToJSONTyped(json, false);
}

export function UserDmPermissionsToJSONTyped(value?: UserDmPermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_dm': value['canDm'],
    };
}

