/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';
import type { UserResultByScreenNameCore } from './UserResultByScreenNameCore';
import {
    UserResultByScreenNameCoreFromJSON,
    UserResultByScreenNameCoreFromJSONTyped,
    UserResultByScreenNameCoreToJSON,
    UserResultByScreenNameCoreToJSONTyped,
} from './UserResultByScreenNameCore';
import type { UserResultByScreenNameLegacy } from './UserResultByScreenNameLegacy';
import {
    UserResultByScreenNameLegacyFromJSON,
    UserResultByScreenNameLegacyFromJSONTyped,
    UserResultByScreenNameLegacyToJSON,
    UserResultByScreenNameLegacyToJSONTyped,
} from './UserResultByScreenNameLegacy';
import type { UserResultPrivacy } from './UserResultPrivacy';
import {
    UserResultPrivacyFromJSON,
    UserResultPrivacyFromJSONTyped,
    UserResultPrivacyToJSON,
    UserResultPrivacyToJSONTyped,
} from './UserResultPrivacy';
import type { UserResultRelationshipPerspectives } from './UserResultRelationshipPerspectives';
import {
    UserResultRelationshipPerspectivesFromJSON,
    UserResultRelationshipPerspectivesFromJSONTyped,
    UserResultRelationshipPerspectivesToJSON,
    UserResultRelationshipPerspectivesToJSONTyped,
} from './UserResultRelationshipPerspectives';

/**
 * 
 * @export
 * @interface UserResultByScreenNameResult
 */
export interface UserResultByScreenNameResult {
    /**
     * 
     * @type {TypeName}
     * @memberof UserResultByScreenNameResult
     */
    typename: TypeName;
    /**
     * 
     * @type {UserResultByScreenNameCore}
     * @memberof UserResultByScreenNameResult
     */
    core: UserResultByScreenNameCore;
    /**
     * 
     * @type {string}
     * @memberof UserResultByScreenNameResult
     */
    id: string;
    /**
     * 
     * @type {UserResultByScreenNameLegacy}
     * @memberof UserResultByScreenNameResult
     */
    legacy?: UserResultByScreenNameLegacy;
    /**
     * 
     * @type {UserResultPrivacy}
     * @memberof UserResultByScreenNameResult
     */
    privacy: UserResultPrivacy;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UserResultByScreenNameResult
     */
    profilemodules: { [key: string]: any; };
    /**
     * 
     * @type {UserResultRelationshipPerspectives}
     * @memberof UserResultByScreenNameResult
     */
    relationshipPerspectives: UserResultRelationshipPerspectives;
    /**
     * 
     * @type {string}
     * @memberof UserResultByScreenNameResult
     */
    restId: string;
}



/**
 * Check if a given object implements the UserResultByScreenNameResult interface.
 */
export function instanceOfUserResultByScreenNameResult(value: object): value is UserResultByScreenNameResult {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    if (!('core' in value) || value['core'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('privacy' in value) || value['privacy'] === undefined) return false;
    if (!('profilemodules' in value) || value['profilemodules'] === undefined) return false;
    if (!('relationshipPerspectives' in value) || value['relationshipPerspectives'] === undefined) return false;
    if (!('restId' in value) || value['restId'] === undefined) return false;
    return true;
}

export function UserResultByScreenNameResultFromJSON(json: any): UserResultByScreenNameResult {
    return UserResultByScreenNameResultFromJSONTyped(json, false);
}

export function UserResultByScreenNameResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResultByScreenNameResult {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'core': UserResultByScreenNameCoreFromJSON(json['core']),
        'id': json['id'],
        'legacy': json['legacy'] == null ? undefined : UserResultByScreenNameLegacyFromJSON(json['legacy']),
        'privacy': UserResultPrivacyFromJSON(json['privacy']),
        'profilemodules': json['profilemodules'],
        'relationshipPerspectives': UserResultRelationshipPerspectivesFromJSON(json['relationship_perspectives']),
        'restId': json['rest_id'],
    };
}

export function UserResultByScreenNameResultToJSON(json: any): UserResultByScreenNameResult {
    return UserResultByScreenNameResultToJSONTyped(json, false);
}

export function UserResultByScreenNameResultToJSONTyped(value?: UserResultByScreenNameResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
        'core': UserResultByScreenNameCoreToJSON(value['core']),
        'id': value['id'],
        'legacy': UserResultByScreenNameLegacyToJSON(value['legacy']),
        'privacy': UserResultPrivacyToJSON(value['privacy']),
        'profilemodules': value['profilemodules'],
        'relationship_perspectives': UserResultRelationshipPerspectivesToJSON(value['relationshipPerspectives']),
        'rest_id': value['restId'],
    };
}

