/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCore
 */
export interface UserCore {
    /**
     * 
     * @type {string}
     * @memberof UserCore
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof UserCore
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserCore
     */
    screenName: string;
}

/**
 * Check if a given object implements the UserCore interface.
 */
export function instanceOfUserCore(value: object): value is UserCore {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('screenName' in value) || value['screenName'] === undefined) return false;
    return true;
}

export function UserCoreFromJSON(json: any): UserCore {
    return UserCoreFromJSONTyped(json, false);
}

export function UserCoreFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCore {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'],
        'name': json['name'],
        'screenName': json['screen_name'],
    };
}

export function UserCoreToJSON(json: any): UserCore {
    return UserCoreToJSONTyped(json, false);
}

export function UserCoreToJSONTyped(value?: UserCore | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'name': value['name'],
        'screen_name': value['screenName'],
    };
}

