/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAvatar
 */
export interface UserAvatar {
    /**
     * 
     * @type {string}
     * @memberof UserAvatar
     */
    imageUrl: string;
}

/**
 * Check if a given object implements the UserAvatar interface.
 */
export function instanceOfUserAvatar(value: object): value is UserAvatar {
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function UserAvatarFromJSON(json: any): UserAvatar {
    return UserAvatarFromJSONTyped(json, false);
}

export function UserAvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAvatar {
    if (json == null) {
        return json;
    }
    return {
        
        'imageUrl': json['image_url'],
    };
}

export function UserAvatarToJSON(json: any): UserAvatar {
    return UserAvatarToJSONTyped(json, false);
}

export function UserAvatarToJSONTyped(value?: UserAvatar | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image_url': value['imageUrl'],
    };
}

