/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRelationshipPerspectives
 */
export interface UserRelationshipPerspectives {
    /**
     * 
     * @type {boolean}
     * @memberof UserRelationshipPerspectives
     */
    blockedBy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserRelationshipPerspectives
     */
    blocking?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserRelationshipPerspectives
     */
    followedBy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserRelationshipPerspectives
     */
    following?: boolean;
}

/**
 * Check if a given object implements the UserRelationshipPerspectives interface.
 */
export function instanceOfUserRelationshipPerspectives(value: object): value is UserRelationshipPerspectives {
    return true;
}

export function UserRelationshipPerspectivesFromJSON(json: any): UserRelationshipPerspectives {
    return UserRelationshipPerspectivesFromJSONTyped(json, false);
}

export function UserRelationshipPerspectivesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRelationshipPerspectives {
    if (json == null) {
        return json;
    }
    return {
        
        'blockedBy': json['blocked_by'] == null ? undefined : json['blocked_by'],
        'blocking': json['blocking'] == null ? undefined : json['blocking'],
        'followedBy': json['followed_by'] == null ? undefined : json['followed_by'],
        'following': json['following'] == null ? undefined : json['following'],
    };
}

export function UserRelationshipPerspectivesToJSON(json: any): UserRelationshipPerspectives {
    return UserRelationshipPerspectivesToJSONTyped(json, false);
}

export function UserRelationshipPerspectivesToJSONTyped(value?: UserRelationshipPerspectives | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blocked_by': value['blockedBy'],
        'blocking': value['blocking'],
        'followed_by': value['followedBy'],
        'following': value['following'],
    };
}

