/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserResultRelationshipPerspectives
 */
export interface UserResultRelationshipPerspectives {
    /**
     * 
     * @type {boolean}
     * @memberof UserResultRelationshipPerspectives
     */
    blockedBy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserResultRelationshipPerspectives
     */
    blocking?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserResultRelationshipPerspectives
     */
    followedBy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserResultRelationshipPerspectives
     */
    following?: boolean;
}

/**
 * Check if a given object implements the UserResultRelationshipPerspectives interface.
 */
export function instanceOfUserResultRelationshipPerspectives(value: object): value is UserResultRelationshipPerspectives {
    return true;
}

export function UserResultRelationshipPerspectivesFromJSON(json: any): UserResultRelationshipPerspectives {
    return UserResultRelationshipPerspectivesFromJSONTyped(json, false);
}

export function UserResultRelationshipPerspectivesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResultRelationshipPerspectives {
    if (json == null) {
        return json;
    }
    return {
        
        'blockedBy': json['blocked_by'] == null ? undefined : json['blocked_by'],
        'blocking': json['blocking'] == null ? undefined : json['blocking'],
        'followedBy': json['followed_by'] == null ? undefined : json['followed_by'],
        'following': json['following'] == null ? undefined : json['following'],
    };
}

export function UserResultRelationshipPerspectivesToJSON(json: any): UserResultRelationshipPerspectives {
    return UserResultRelationshipPerspectivesToJSONTyped(json, false);
}

export function UserResultRelationshipPerspectivesToJSONTyped(value?: UserResultRelationshipPerspectives | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blocked_by': value['blockedBy'],
        'blocking': value['blocking'],
        'followed_by': value['followedBy'],
        'following': value['following'],
    };
}

