/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLocation
 */
export interface UserLocation {
    /**
     * 
     * @type {string}
     * @memberof UserLocation
     */
    location: string;
}

/**
 * Check if a given object implements the UserLocation interface.
 */
export function instanceOfUserLocation(value: object): value is UserLocation {
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function UserLocationFromJSON(json: any): UserLocation {
    return UserLocationFromJSONTyped(json, false);
}

export function UserLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['location'],
    };
}

export function UserLocationToJSON(json: any): UserLocation {
    return UserLocationToJSONTyped(json, false);
}

export function UserLocationToJSONTyped(value?: UserLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': value['location'],
    };
}

