/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRelationshipPerspectives } from './UserRelationshipPerspectives';
import {
    UserRelationshipPerspectivesFromJSON,
    UserRelationshipPerspectivesFromJSONTyped,
    UserRelationshipPerspectivesToJSON,
    UserRelationshipPerspectivesToJSONTyped,
} from './UserRelationshipPerspectives';
import type { UserHighlightsInfo } from './UserHighlightsInfo';
import {
    UserHighlightsInfoFromJSON,
    UserHighlightsInfoFromJSONTyped,
    UserHighlightsInfoToJSON,
    UserHighlightsInfoToJSONTyped,
} from './UserHighlightsInfo';
import type { TypeName } from './TypeName';
import {
    TypeNameFromJSON,
    TypeNameFromJSONTyped,
    TypeNameToJSON,
    TypeNameToJSONTyped,
} from './TypeName';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
    UserProfileToJSONTyped,
} from './UserProfile';
import type { ProfileBio } from './ProfileBio';
import {
    ProfileBioFromJSON,
    ProfileBioFromJSONTyped,
    ProfileBioToJSON,
    ProfileBioToJSONTyped,
} from './ProfileBio';
import type { UserLegacyExtendedProfile } from './UserLegacyExtendedProfile';
import {
    UserLegacyExtendedProfileFromJSON,
    UserLegacyExtendedProfileFromJSONTyped,
    UserLegacyExtendedProfileToJSON,
    UserLegacyExtendedProfileToJSONTyped,
} from './UserLegacyExtendedProfile';
import type { UserTipJarSettings } from './UserTipJarSettings';
import {
    UserTipJarSettingsFromJSON,
    UserTipJarSettingsFromJSONTyped,
    UserTipJarSettingsToJSON,
    UserTipJarSettingsToJSONTyped,
} from './UserTipJarSettings';
import type { UserVerification } from './UserVerification';
import {
    UserVerificationFromJSON,
    UserVerificationFromJSONTyped,
    UserVerificationToJSON,
    UserVerificationToJSONTyped,
} from './UserVerification';
import type { UserAvatar } from './UserAvatar';
import {
    UserAvatarFromJSON,
    UserAvatarFromJSONTyped,
    UserAvatarToJSON,
    UserAvatarToJSONTyped,
} from './UserAvatar';
import type { UserPrivacy } from './UserPrivacy';
import {
    UserPrivacyFromJSON,
    UserPrivacyFromJSONTyped,
    UserPrivacyToJSON,
    UserPrivacyToJSONTyped,
} from './UserPrivacy';
import type { UserVerificationInfo } from './UserVerificationInfo';
import {
    UserVerificationInfoFromJSON,
    UserVerificationInfoFromJSONTyped,
    UserVerificationInfoToJSON,
    UserVerificationInfoToJSONTyped,
} from './UserVerificationInfo';
import type { UserLocation } from './UserLocation';
import {
    UserLocationFromJSON,
    UserLocationFromJSONTyped,
    UserLocationToJSON,
    UserLocationToJSONTyped,
} from './UserLocation';
import type { UserLegacy } from './UserLegacy';
import {
    UserLegacyFromJSON,
    UserLegacyFromJSONTyped,
    UserLegacyToJSON,
    UserLegacyToJSONTyped,
} from './UserLegacy';
import type { UserCore } from './UserCore';
import {
    UserCoreFromJSON,
    UserCoreFromJSONTyped,
    UserCoreToJSON,
    UserCoreToJSONTyped,
} from './UserCore';
import type { UserMediaPermissions } from './UserMediaPermissions';
import {
    UserMediaPermissionsFromJSON,
    UserMediaPermissionsFromJSONTyped,
    UserMediaPermissionsToJSON,
    UserMediaPermissionsToJSONTyped,
} from './UserMediaPermissions';
import type { UserProfessional } from './UserProfessional';
import {
    UserProfessionalFromJSON,
    UserProfessionalFromJSONTyped,
    UserProfessionalToJSON,
    UserProfessionalToJSONTyped,
} from './UserProfessional';
import type { UserDmPermissions } from './UserDmPermissions';
import {
    UserDmPermissionsFromJSON,
    UserDmPermissionsFromJSONTyped,
    UserDmPermissionsToJSON,
    UserDmPermissionsToJSONTyped,
} from './UserDmPermissions';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {TypeName}
     * @memberof User
     */
    typename: TypeName;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof User
     */
    affiliatesHighlightedLabel?: { [key: string]: any; };
    /**
     * 
     * @type {UserAvatar}
     * @memberof User
     */
    avatar?: UserAvatar;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof User
     */
    businessAccount?: { [key: string]: any; };
    /**
     * 
     * @type {UserCore}
     * @memberof User
     */
    core?: UserCore;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    creatorSubscriptionsCount?: number;
    /**
     * 
     * @type {UserDmPermissions}
     * @memberof User
     */
    dmPermissions?: UserDmPermissions;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    hasGraduatedAccess?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    hasHiddenLikesOnProfile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    hasHiddenSubscriptionsOnProfile?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    hasNftAvatar?: boolean;
    /**
     * 
     * @type {UserHighlightsInfo}
     * @memberof User
     */
    highlightsInfo?: UserHighlightsInfo;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isBlueVerified: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isProfileTranslatable?: boolean;
    /**
     * 
     * @type {UserLegacy}
     * @memberof User
     */
    legacy: UserLegacy;
    /**
     * 
     * @type {UserLegacyExtendedProfile}
     * @memberof User
     */
    legacyExtendedProfile?: UserLegacyExtendedProfile;
    /**
     * 
     * @type {UserLocation}
     * @memberof User
     */
    location?: UserLocation;
    /**
     * 
     * @type {UserMediaPermissions}
     * @memberof User
     */
    mediaPermissions?: UserMediaPermissions;
    /**
     * 
     * @type {UserParodyCommentaryFanLabelEnum}
     * @memberof User
     */
    parodyCommentaryFanLabel?: UserParodyCommentaryFanLabelEnum;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    premiumGiftingEligible?: boolean;
    /**
     * 
     * @type {UserPrivacy}
     * @memberof User
     */
    privacy?: UserPrivacy;
    /**
     * 
     * @type {UserProfessional}
     * @memberof User
     */
    professional?: UserProfessional;
    /**
     * 
     * @type {ProfileBio}
     * @memberof User
     */
    profileBio?: ProfileBio;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    profileDescriptionLanguage?: string;
    /**
     * 
     * @type {UserProfileImageShapeEnum}
     * @memberof User
     */
    profileImageShape: UserProfileImageShapeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    profileSortEnabled?: boolean;
    /**
     * 
     * @type {UserRelationshipPerspectives}
     * @memberof User
     */
    relationshipPerspectives?: UserRelationshipPerspectives;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    restId: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    superFollowEligible?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    superFollowedBy?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    superFollowing?: boolean;
    /**
     * 
     * @type {UserProfile}
     * @memberof User
     */
    superFollowsUserProfile?: UserProfile;
    /**
     * 
     * @type {UserTipJarSettings}
     * @memberof User
     */
    tipjarSettings?: UserTipJarSettings;
    /**
     * 
     * @type {number}
     * @memberof User
     */
    userSeedTweetCount?: number;
    /**
     * 
     * @type {UserVerification}
     * @memberof User
     */
    verification?: UserVerification;
    /**
     * 
     * @type {UserVerificationInfo}
     * @memberof User
     */
    verificationInfo?: UserVerificationInfo;
    /**
     * 
     * @type {UserProfile}
     * @memberof User
     */
    verifiedUserProfiles?: UserProfile;
}


/**
 * @export
 */
export const UserParodyCommentaryFanLabelEnum = {
    None: 'None',
    Parody: 'Parody',
    Commentary: 'Commentary',
    Fan: 'Fan'
} as const;
export type UserParodyCommentaryFanLabelEnum = typeof UserParodyCommentaryFanLabelEnum[keyof typeof UserParodyCommentaryFanLabelEnum];

/**
 * @export
 */
export const UserProfileImageShapeEnum = {
    Circle: 'Circle',
    Square: 'Square',
    Hexagon: 'Hexagon'
} as const;
export type UserProfileImageShapeEnum = typeof UserProfileImageShapeEnum[keyof typeof UserProfileImageShapeEnum];


/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    if (!('typename' in value) || value['typename'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isBlueVerified' in value) || value['isBlueVerified'] === undefined) return false;
    if (!('legacy' in value) || value['legacy'] === undefined) return false;
    if (!('profileImageShape' in value) || value['profileImageShape'] === undefined) return false;
    if (!('restId' in value) || value['restId'] === undefined) return false;
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'typename': TypeNameFromJSON(json['__typename']),
        'affiliatesHighlightedLabel': json['affiliates_highlighted_label'] == null ? undefined : json['affiliates_highlighted_label'],
        'avatar': json['avatar'] == null ? undefined : UserAvatarFromJSON(json['avatar']),
        'businessAccount': json['business_account'] == null ? undefined : json['business_account'],
        'core': json['core'] == null ? undefined : UserCoreFromJSON(json['core']),
        'creatorSubscriptionsCount': json['creator_subscriptions_count'] == null ? undefined : json['creator_subscriptions_count'],
        'dmPermissions': json['dm_permissions'] == null ? undefined : UserDmPermissionsFromJSON(json['dm_permissions']),
        'hasGraduatedAccess': json['has_graduated_access'] == null ? undefined : json['has_graduated_access'],
        'hasHiddenLikesOnProfile': json['has_hidden_likes_on_profile'] == null ? undefined : json['has_hidden_likes_on_profile'],
        'hasHiddenSubscriptionsOnProfile': json['has_hidden_subscriptions_on_profile'] == null ? undefined : json['has_hidden_subscriptions_on_profile'],
        'hasNftAvatar': json['has_nft_avatar'] == null ? undefined : json['has_nft_avatar'],
        'highlightsInfo': json['highlights_info'] == null ? undefined : UserHighlightsInfoFromJSON(json['highlights_info']),
        'id': json['id'],
        'isBlueVerified': json['is_blue_verified'],
        'isProfileTranslatable': json['is_profile_translatable'] == null ? undefined : json['is_profile_translatable'],
        'legacy': UserLegacyFromJSON(json['legacy']),
        'legacyExtendedProfile': json['legacy_extended_profile'] == null ? undefined : UserLegacyExtendedProfileFromJSON(json['legacy_extended_profile']),
        'location': json['location'] == null ? undefined : UserLocationFromJSON(json['location']),
        'mediaPermissions': json['media_permissions'] == null ? undefined : UserMediaPermissionsFromJSON(json['media_permissions']),
        'parodyCommentaryFanLabel': json['parody_commentary_fan_label'] == null ? undefined : json['parody_commentary_fan_label'],
        'premiumGiftingEligible': json['premium_gifting_eligible'] == null ? undefined : json['premium_gifting_eligible'],
        'privacy': json['privacy'] == null ? undefined : UserPrivacyFromJSON(json['privacy']),
        'professional': json['professional'] == null ? undefined : UserProfessionalFromJSON(json['professional']),
        'profileBio': json['profile_bio'] == null ? undefined : ProfileBioFromJSON(json['profile_bio']),
        'profileDescriptionLanguage': json['profile_description_language'] == null ? undefined : json['profile_description_language'],
        'profileImageShape': json['profile_image_shape'],
        'profileSortEnabled': json['profile_sort_enabled'] == null ? undefined : json['profile_sort_enabled'],
        'relationshipPerspectives': json['relationship_perspectives'] == null ? undefined : UserRelationshipPerspectivesFromJSON(json['relationship_perspectives']),
        'restId': json['rest_id'],
        'superFollowEligible': json['super_follow_eligible'] == null ? undefined : json['super_follow_eligible'],
        'superFollowedBy': json['super_followed_by'] == null ? undefined : json['super_followed_by'],
        'superFollowing': json['super_following'] == null ? undefined : json['super_following'],
        'superFollowsUserProfile': json['super_follows_user_profile'] == null ? undefined : UserProfileFromJSON(json['super_follows_user_profile']),
        'tipjarSettings': json['tipjar_settings'] == null ? undefined : UserTipJarSettingsFromJSON(json['tipjar_settings']),
        'userSeedTweetCount': json['user_seed_tweet_count'] == null ? undefined : json['user_seed_tweet_count'],
        'verification': json['verification'] == null ? undefined : UserVerificationFromJSON(json['verification']),
        'verificationInfo': json['verification_info'] == null ? undefined : UserVerificationInfoFromJSON(json['verification_info']),
        'verifiedUserProfiles': json['verified_user_profiles'] == null ? undefined : UserProfileFromJSON(json['verified_user_profiles']),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '__typename': TypeNameToJSON(value['typename']),
        'affiliates_highlighted_label': value['affiliatesHighlightedLabel'],
        'avatar': UserAvatarToJSON(value['avatar']),
        'business_account': value['businessAccount'],
        'core': UserCoreToJSON(value['core']),
        'creator_subscriptions_count': value['creatorSubscriptionsCount'],
        'dm_permissions': UserDmPermissionsToJSON(value['dmPermissions']),
        'has_graduated_access': value['hasGraduatedAccess'],
        'has_hidden_likes_on_profile': value['hasHiddenLikesOnProfile'],
        'has_hidden_subscriptions_on_profile': value['hasHiddenSubscriptionsOnProfile'],
        'has_nft_avatar': value['hasNftAvatar'],
        'highlights_info': UserHighlightsInfoToJSON(value['highlightsInfo']),
        'id': value['id'],
        'is_blue_verified': value['isBlueVerified'],
        'is_profile_translatable': value['isProfileTranslatable'],
        'legacy': UserLegacyToJSON(value['legacy']),
        'legacy_extended_profile': UserLegacyExtendedProfileToJSON(value['legacyExtendedProfile']),
        'location': UserLocationToJSON(value['location']),
        'media_permissions': UserMediaPermissionsToJSON(value['mediaPermissions']),
        'parody_commentary_fan_label': value['parodyCommentaryFanLabel'],
        'premium_gifting_eligible': value['premiumGiftingEligible'],
        'privacy': UserPrivacyToJSON(value['privacy']),
        'professional': UserProfessionalToJSON(value['professional']),
        'profile_bio': ProfileBioToJSON(value['profileBio']),
        'profile_description_language': value['profileDescriptionLanguage'],
        'profile_image_shape': value['profileImageShape'],
        'profile_sort_enabled': value['profileSortEnabled'],
        'relationship_perspectives': UserRelationshipPerspectivesToJSON(value['relationshipPerspectives']),
        'rest_id': value['restId'],
        'super_follow_eligible': value['superFollowEligible'],
        'super_followed_by': value['superFollowedBy'],
        'super_following': value['superFollowing'],
        'super_follows_user_profile': UserProfileToJSON(value['superFollowsUserProfile']),
        'tipjar_settings': UserTipJarSettingsToJSON(value['tipjarSettings']),
        'user_seed_tweet_count': value['userSeedTweetCount'],
        'verification': UserVerificationToJSON(value['verification']),
        'verification_info': UserVerificationInfoToJSON(value['verificationInfo']),
        'verified_user_profiles': UserProfileToJSON(value['verifiedUserProfiles']),
    };
}

