/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPrivacy
 */
export interface UserPrivacy {
    /**
     * 
     * @type {boolean}
     * @memberof UserPrivacy
     */
    _protected: boolean;
}

/**
 * Check if a given object implements the UserPrivacy interface.
 */
export function instanceOfUserPrivacy(value: object): value is UserPrivacy {
    if (!('_protected' in value) || value['_protected'] === undefined) return false;
    return true;
}

export function UserPrivacyFromJSON(json: any): UserPrivacy {
    return UserPrivacyFromJSONTyped(json, false);
}

export function UserPrivacyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPrivacy {
    if (json == null) {
        return json;
    }
    return {
        
        '_protected': json['protected'],
    };
}

export function UserPrivacyToJSON(json: any): UserPrivacy {
    return UserPrivacyToJSONTyped(json, false);
}

export function UserPrivacyToJSONTyped(value?: UserPrivacy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'protected': value['_protected'],
    };
}

