/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserVerification
 */
export interface UserVerification {
    /**
     * 
     * @type {boolean}
     * @memberof UserVerification
     */
    verified: boolean;
    /**
     * 
     * @type {UserVerificationVerifiedTypeEnum}
     * @memberof UserVerification
     */
    verifiedType?: UserVerificationVerifiedTypeEnum;
}


/**
 * @export
 */
export const UserVerificationVerifiedTypeEnum = {
    Business: 'Business',
    Government: 'Government'
} as const;
export type UserVerificationVerifiedTypeEnum = typeof UserVerificationVerifiedTypeEnum[keyof typeof UserVerificationVerifiedTypeEnum];


/**
 * Check if a given object implements the UserVerification interface.
 */
export function instanceOfUserVerification(value: object): value is UserVerification {
    if (!('verified' in value) || value['verified'] === undefined) return false;
    return true;
}

export function UserVerificationFromJSON(json: any): UserVerification {
    return UserVerificationFromJSONTyped(json, false);
}

export function UserVerificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserVerification {
    if (json == null) {
        return json;
    }
    return {
        
        'verified': json['verified'],
        'verifiedType': json['verified_type'] == null ? undefined : json['verified_type'],
    };
}

export function UserVerificationToJSON(json: any): UserVerification {
    return UserVerificationToJSONTyped(json, false);
}

export function UserVerificationToJSONTyped(value?: UserVerification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verified': value['verified'],
        'verified_type': value['verifiedType'],
    };
}

