/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SuperFollowUserProfile } from './SuperFollowUserProfile';
import {
    SuperFollowUserProfileFromJSON,
    SuperFollowUserProfileFromJSONTyped,
    SuperFollowUserProfileToJSON,
    SuperFollowUserProfileToJSONTyped,
} from './SuperFollowUserProfile';

/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {SuperFollowUserProfile}
     * @memberof UserProfile
     */
    superFollowsUserProfile: SuperFollowUserProfile;
}

/**
 * Check if a given object implements the UserProfile interface.
 */
export function instanceOfUserProfile(value: object): value is UserProfile {
    if (!('superFollowsUserProfile' in value) || value['superFollowsUserProfile'] === undefined) return false;
    return true;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'superFollowsUserProfile': SuperFollowUserProfileFromJSON(json['super_follows_user_profile']),
    };
}

export function UserProfileToJSON(json: any): UserProfile {
    return UserProfileToJSONTyped(json, false);
}

export function UserProfileToJSONTyped(value?: UserProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'super_follows_user_profile': SuperFollowUserProfileToJSON(value['superFollowsUserProfile']),
    };
}

