/* tslint:disable */
/* eslint-disable */
/**
 * Twitter OpenAPI
 * Twitter OpenAPI(Swagger) specification
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: yuki@yuki0311.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserMediaPermissions
 */
export interface UserMediaPermissions {
    /**
     * 
     * @type {boolean}
     * @memberof UserMediaPermissions
     */
    canMediaTag: boolean;
}

/**
 * Check if a given object implements the UserMediaPermissions interface.
 */
export function instanceOfUserMediaPermissions(value: object): value is UserMediaPermissions {
    if (!('canMediaTag' in value) || value['canMediaTag'] === undefined) return false;
    return true;
}

export function UserMediaPermissionsFromJSON(json: any): UserMediaPermissions {
    return UserMediaPermissionsFromJSONTyped(json, false);
}

export function UserMediaPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMediaPermissions {
    if (json == null) {
        return json;
    }
    return {
        
        'canMediaTag': json['can_media_tag'],
    };
}

export function UserMediaPermissionsToJSON(json: any): UserMediaPermissions {
    return UserMediaPermissionsToJSONTyped(json, false);
}

export function UserMediaPermissionsToJSONTyped(value?: UserMediaPermissions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'can_media_tag': value['canMediaTag'],
    };
}

